version: 2

project_name: pxy

before:
  hooks:
    - go mod tidy

builds:
  - id: pxy
    main: .
    binary: pxy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/hczs/pxy/cmd.version={{ .Version }}
      - -X github.com/hczs/pxy/cmd.commit={{ .Commit }}
      - -X github.com/hczs/pxy/cmd.date={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: pxy
    builds:
      - pxy
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
